# Site settings
title: Black Python Devs
domain: blackpythondevs.com
description: >
  Black Python Devs

# baseurl: / # the subpath of your site, e.g. /blog/
# url: https://blackpythondevs.com # the base hostname & protocol for your site

# Favicon
# favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title, a url and font awesome class.
navigation:
  - text: Home
    url: /
    fa: fa fa-home fa-fw
  - text: Blog
    url: /blog/
    fa: fa fa-newspaper fa-fw
  - text: About Us
    url: /about/
    fa: fa fa-info-circle fa-fw
  - text: Events
    url: /events/
    fa: fa fa-calendar fa-fw
  - text: Community
    url: /community/
    fa: fa fa-users fa-fw
  - text: Support Us
    url: /support/
    fa: fa-solid fa-money-check-dollar

bpdevs:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  social_links:
    - { platform: github, user_url: "https://github.com/BlackPythonDevs/blackpythondevs.github.io" }
    - { platform: discord, user_url: "https://discord.gg/XUc3tFqCT3" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/groups/14336241/" }
    - { platform: mastodon, user_url: "https://mastodon.social/@blackpythondevs" }
    - { platform: youtube, user_url: "https://www.youtube.com/@BlackPythonDevs" }
    - { platform: x, user_url: "https://x.com/blackpythondevs" }
    - { platform: email, user_url: "mailto:contact@blackpythondevs.com" }

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - github-pages
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
# - jekyll-seo-tag
# - jekyll-redirect-from
# - jekyll-remote-theme

exclude:
  - bin
  - CNAME
  - CODE_OF_CONDUCT.md
  - README.md
  - Gemfile*
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - .idea/
  - .gitattributes
  - .gitignore
  - .prettierrc
  - .prettierignore
  - .pytest_cache
  - resources
  - script
  - test
  - vendor
  - venv
  - .venv
  - requirements*.txt
  - pytest.ini
# timezone: America/Toronto

permalink: "/:path/"

collections:
  articles:
    output: true
    permalink: "/:path/"

defaults:
  # - scope:
  #     path: ""
  #   values:
  #     image: /assets/images/cards/default.png
  - scope:
      path: ""
      type: articles
    values:
      layout: article

# Set to `true` to show excerpts on the homepage.
#
show_excerpts: true
