# Site settings
title: Black Python Developers Community
description: >
  blackpythondevs.com

# baseurl: / # the subpath of your site, e.g. /blog/
# url: https://blackpythondevs.com # the base hostname & protocol for your site

# Favicon
# favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title, a url and font awesome class.
navigation:
  - text: Home
    url: /
    fa: fa fa-home fa-fw
  - text: About Us
    url: /about/
    fa: fa fa-info-circle fa-fw
  - text: Events
    url: /events/
    fa: fa fa-calendar fa-fw
  - text: Conferences
    url: /conferences/
    fa: fa fa-microphone fa-fw
  - text: Community
    url: /community/
    fa: fa fa-users fa-fw

bpdevs:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  social_links:
    - { platform: github, user_url: "https://github.com/BlackPythonDevs/blackpythondevs.github.io" }
    - { platform: x, user_url: "https://x.com/blackpythondevs" }

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - github-pages
  - jemoji
  - jekyll-feed
  # - jekyll-seo-tag
  # - jekyll-sitemap

exclude:
  - bin
  - CNAME
  - CODE_OF_CONDUCT.md
  - README.md
  - Gemfile*
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - .idea/
  - .gitattributes
  - .gitignore
  - .prettierrc
  - .prettierignore
  - resources
  - script
  - test
  - vendor
  - venv
  - .venv
  - requirements*.txt
  - pytest.ini
  - _membership/schema.json
  - _membership/users.json
# timezone: America/Toronto

permalink: "/:path/"

collections:
  articles:
    output: true
    permalink: "/:path/"
  membership:
    output: false
    permalink: "/:path/"

defaults:
  # - scope:
  #     path: ""
  #   values:
  #     image: /assets/images/cards/default.png
  - scope:
      path: ""
      type: articles
    values:
      layout: article
